### ISSUE TITLE
Layout props don't work

### ISSUE THREAD

**Issue by ElRochito** [TheDoctor0/inertia-vue-typescript-example#3]
Hi! 

I've clone your project, layout is ignored when rendering.

In DOM, we see only h1 tag

**Comment by TheDoctor0** [comment]
Hello.
That's actually the point, this repository was created to replicate the issue with layout rendering when using TypeScript class-style components. You can check this [pull request](https://github.com/inertiajs/inertia-vue/pull/108).

**Comment by ElRochito** [comment]
Oh ok! Nice! Wait and see Mister Reinink :)
